
title: Muzi
description: Muzi is a theme for Jekyll/GitHub Pages distributed under the MIT license.

logo: /assets/logo_blue.svg

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"